name: Deploy to Amazon Linux EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Copy files to EC2 home directory
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "."
          target: "/home/ec2-user"

      - name: Move files to Nginx folder
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo rm -rf /usr/share/nginx/html/*
            sudo cp -r /home/ec2-user/* /usr/share/nginx/html/
            sudo chown -R nginx:nginx /usr/share/nginx/html
            sudo chmod -R 755 /usr/share/nginx/html
            sudo systemctl restart nginx
